[package]
name = "borrow_checker"
version = "0.1.0"
authors = ["ohmycloud"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
